//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : CadastroTipoQuarto.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class CadastroTipoQuarto {
	public void gravar(){
	}
	public void buscar(){
	}
	public void excluir(){
	}
}
