//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : CadrastroCheckOut.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class CadrastroCheckOut {
	public void gravar(){
	}
}
