//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraRelatorioFluxoCaixa.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraRelatorioFluxoCaixa {
	public void gerar(){
	}
}
