//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraGerenciarDespesasDoCliente.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraGerenciarDespesasDoCliente {
	public void cadastrar(){
	}
	public void validarDados(){
	}
	public void excluir(){
	}
	public void buscar(){
	}
	public void alterar(){
	}
}
