//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraManterTipoDeQuarto.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraManterTipoDeQuarto {
	public void cadastrar(){
	}
	public void validaDados(){
	}
	public void buscar(){
	}
	public void editar(){
	}
	public void excluir(){
	}
}
