//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraManterPessoa.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraManterPessoa {
	public void cadastrar(){
	}
	public void validarDados(){
	}
	public void buscar(){
	}
	public void excluir(){
	}
	public void editar(){
	}
	public void buscarDadosPeriodo(string dataFinal:string dataInicio){
	}
}
