//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraCheckIn.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraCheckIn {
	public void buscar(){
	}
	public void cadastrar(){
	}
	public void buscarDadosPeriodo(){
	}
}
