//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraAutenticarUsuario.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraAutenticarUsuario {
	public void autenticar(){
	}
	public void validar(){
	}
}
