//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraEfetuarPagamento.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraEfetuarPagamento {
	public void buscar(){
	}
	public void atualizar(){
	}
}
