//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladoraCheckOut.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class ControladoraCheckOut {
	public void cadastrar(){
	}
	public void buscarDadosPeriodo(string dataFinal:string dataInicio){
	}
}
