//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Despesa.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Despesa {
	public double valorTotal ;
	public date dataAbertura ;
	public date dataLiberacao ;
	public date dataCadsatro ;
	public boolean cancelado ;
}
