//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : FomaPagamento.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class FomaPagamento {
	public String descricao ;
	public String observacao ;
	public integer numeroMaximoParcelas ;
	public boolean ativo ;
}
