//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : GeradorRelatorioFluxoCaixa.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class GeradorRelatorioFluxoCaixa {
	public void gerar(){
	}
	public void buscarDadosPeriodo(string dataFinal:string dataInicio){
	}
}
