//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Pagamento.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Pagamento {
	public date dataPagamento ;
	public integer numeroParcela ;
	public enum statusPagamento ;
	public date dataCadastro ;
	public date dataPrevista ;
	public double valorParcela ;
}
