//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Pessoa {
	public String nome ;
	public String endereco ;
	public String cpf ;
	public String cnpj ;
	public String telefoneFixo ;
	public String telefoneMovel ;
	public String emailPrimario ;
	public String emailSecundario ;
	public date dataNascimento ;
	public String estadoCivil ;
	public char sexo ;
	public String cargo ;
	public date dataCadastro ;
	public string rg ;
	public boolean eFuncionario ;
}
