//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Quarto.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Quarto {
	public integer capacidade ;
	public String descricao ;
	public String observacao ;
	public enum statusAcessorio ;
	public boolean ativo ;
}
