//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Reserva.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Reserva {
	public enum status ;
	public double valorTotal ;
	public double subTotal ;
	public string observacao ;
	public date dataLiberacao ;
	public date dataEntrada ;
	public String dataSaida ;
	public String dataCadastro ;
	public boolean ativo ;
}
