//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Servico.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Servico {
	public String descricao ;
	public string observacao ;
	public double valor ;
	public boolean ativo ;
}
