//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaEfetuarPagamento.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaEfetuarPagamento {
	public void pagar(){
	}
	public void buscar(){
	}
}
