//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaCheckIn.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaCheckIn {
	public void cadastrar(){
	}
	public void atualizar(){
	}
	public void realizar(){
	}
}
