//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaManterPessoa.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaManterPessoa {
	public void cadastrar(){
	}
	public void consultar(){
	}
	public void excluir(){
	}
	public void editar(){
	}
}
