//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaAutenticarUsuario.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaAutenticarUsuario {
	public void autenticar(){
	}
}
