//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaCheckOut.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaCheckOut {
	public void realizar(){
	}
}
