//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaRelatorioFluxoHospede.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaRelatorioFluxoHospede {
	public void gerarRelatorio(){
	}
}
