//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaTipoServico.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TelaTipoServico {
	public void cadastra(){
	}
	public void consultar(){
	}
	public void editar(){
	}
}
