//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoDeServico.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TipoDeServico {
	public String descricao ;
	public string observacao ;
}
