//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoDeQuarto.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class TipoDeQuarto {
	public String descricao ;
	public String observacao ;
	public double valor ;
}
