//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.cs
//  @ Date : 25/03/2015
//  @ Author : 
//
//


public class Usuario {
	public String nome ;
	public String senha ;
	public enum nivelAcesso ;
	public date dataCadastro ;
	public boolean ativo ;
}
